// locations.ts

export const countries = {
  Singapore: ["Singapore"],
  Japan: ["Tokyo", "Osaka", "Kyoto", "Nagoya", "Sapporo", "Fukuoka"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu"],
  China: [
    "Beijing",
    "Shanghai",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Hangzhou",
  ],
  India: [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata",
  ],
  Thailand: ["Bangkok", "Chiang Mai", "Phuket"],
  Malaysia: ["Kuala Lumpur", "George Town", "Johor Bahru"],
  Indonesia: ["Jakarta", "Surabaya", "Bandung", "Denpasar"],
  Vietnam: ["Ho Chi Minh City", "Hanoi", "Da Nang"],
  "United Kingdom": [
    "London",
    "Manchester",
    "Birmingham",
    "Edinburgh",
    "Glasgow",
  ],
  France: ["Paris", "Lyon", "Marseille", "Nice"],
  Germany: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne"],
  Italy: ["Rome", "Milan", "Naples", "Florence", "Venice"],
  Spain: ["Madrid", "Barcelona", "Valencia", "Seville"],
  Netherlands: ["Amsterdam", "Rotterdam", "The Hague"],
  "United States": [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "San Francisco",
    "Seattle",
    "Miami",
    "Boston",
  ],
  Canada: ["Toronto", "Vancouver", "Montreal", "Calgary"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi"],
  "South Africa": ["Cape Town", "Johannesburg", "Durban"],
  Brazil: ["São Paulo", "Rio de Janeiro", "Brasília"],
  Mexico: ["Mexico City", "Guadalajara", "Monterrey"],
};